### ISSUE TITLE
Kong docker-compose up

### ISSUE THREAD

**Issue by vijaay3d** [Kong/docker-kong#133] opened 2018-01-10 19:42 UTC
I am running kong on an EC2 Amazon Linux, docker-compose up keeps timeout at health check. 
I assume docker comose is opening all the ports and firewall for inter-container communication?  

kong_1            | 2018/01/10 19:37:55 kong-8000.health exited with error: waitid: no child processes
nginx-lb_1        | time="2018-01-10T19:38:04Z" level=debug msg="nginx.health.RunWithTimeout start"
nginx-lb_1        | time="2018-01-10T19:38:04Z" level=debug msg=nginx.health.Cmd.Start
nginx-lb_1        | time="2018-01-10T19:38:04Z" level=debug msg="nginx.health.run waiting for PID 892: "
nginx-lb_1        | 127.0.0.1 - - [10/Jan/2018:19:38:04 +0000] "GET /health HTTP/1.1" 200 103 "-" "curl/7.52.1"

**Comment by hutchic** [comment] 2019-02-19 19:19
I'm unable to reproduce using ami-035be7bafff33b6b6 in us-east

```
sudo yum update
sudo amazon-linux-extras install docker git
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
git clone https://github.com/Kong/docker-kong.git
cd docker-kong/compose
docker-compose up -d
```

```
docker-compose ps
          Name                         Command                  State                                            Ports
-----------------------------------------------------------------------------------------------------------------------------------------------------------
compose_db_1                docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
compose_kong-migrations_1   /docker-entrypoint.sh kong ...   Exit 0
compose_kong_1              /docker-entrypoint.sh kong ...   Up

curl -I localhost:8001
HTTP/1.1 200 OK
Server: openresty/1.13.6.2
Date: Tue, 19 Feb 2019 19:16:45 GMT
Content-Type: application/json
Connection: keep-alive
Access-Control-Allow-Origin: *
```

This line `"GET /health HTTP/1.1" 200 103 "-" "curl/7.52.1"` from your pasted log looks like it should have registered as healthy

**Comment by hutchic** [comment] 2019-03-21 16:27
We now have tests that validate our `docker-compose up` works so I'm going to go ahead and close this issue at this time

**Closed by hutchic** 2019-03-21 16:27 UTC
