### ISSUE TITLE
Unable to restart nginx successfully during a compose scale

### ISSUE THREAD

**Issue by andymed-dml** [Kong/docker-kong#141] opened 2018-02-07 16:54 UTC
Hi.

I'm trying to run the compose example of this repo but cannot seem to get the scaling to work automatically.

I've taken the example today run it and can access the Kong instance nicely. But when I issue the scale command and look at the nginx logs I see the following:

time="2018-02-07T16:39:33Z" level=debug msg="kong-8444.health.run waiting for PID 49: "
time="2018-02-07T16:39:33Z" level=debug msg="kong-8443.health.run waiting for PID 50: "
time="2018-02-07T16:39:33Z" level=info msg="2018/02/07 16:39:33 [notice] 85#85: signal process started" backend=kong-8000 process=onChange
2018/02/07 16:39:33 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address already in use)
time="2018-02-07T16:39:33Z" level=debug msg="kong-8444.health.run complete"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8444.health.RunWithTimeout end"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8443.health.run complete"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8443.health.RunWithTimeout end"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8000.health.run complete"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8000.health.RunWithTimeout end"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8001.health.run complete"
time="2018-02-07T16:39:33Z" level=debug msg="kong-8001.health.RunWithTimeout end"
2018/02/07 16:39:33 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/02/07 16:39:33 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/02/07 16:39:33 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/02/07 16:39:33 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/02/07 16:39:33 [emerg] 23#23: still could not bind()
time="2018-02-07T16:39:39Z" level=debug msg="nginx.health.RunWithTimeout start"
time="2018-02-07T16:39:39Z" level=debug msg=nginx.health.Cmd.Start
time="2018-02-07T16:39:39Z" level=debug msg="nginx.health.run waiting for PID 91: "

Which seems to imply that the port is in use and the 2nd Kong server is not added to the load balancer. And I see this when have made no changes to the my clone.

If I issue an nginx -s reload (when I've touched the config file) I see the same issue.

If I start and stop nginx rather than a reload it works (picks up the 2nd instance) - but this isn't want I want because it means there's a break in the service while the container is restarted.

If I try to change the port from 80 to something greater that 1024 (say 8888) it has exactly the same issue other than binding to port 8888 rather than 80 is the offending error.

Does anyone know what I've done wrong?

Thanks in advance,
Andy

**Comment by andymed-dml** [comment] 2018-02-08 10:38
I have managed to get around this by changing ONLY the health check to run off another port (8888 in my case) and this seems now to not have the conflict. So my **nginx** containerpilot.json contains this:

 "services": [
    {
      "name": "nginx",
      "port": 80,
      "interfaces": ["eth1", "eth0"],
      "health": "/usr/bin/curl -o /dev/null --fail -s http://localhost:8888/health",
      "poll": 10,
      "ttl": 25
    }
  ],

and my nginx.conf.ctmpl contains:

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    charset UTF-8;

    server {
        listen 8888;
        location /health {
            # requires http_stub_status_module
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}

Now I think that makes sense to me (and works so I can see the scaling up and down behaving as expected without loss of requests) but is this a bug in the templates or have I just done something wrong?

Cheers,
Andy

**Comment by hutchic** [comment] 2019-02-15 18:26
related: https://github.com/Kong/docker-kong/pull/229

**Comment by gszr** [comment] 2021-04-14 17:29
Duplicate of https://github.com/Kong/docker-kong/issues/221.

**Closed by gszr** 2021-04-14 17:29 UTC
