### ISSUE TITLE
docker-entrypoint.sh: line 29: exec: su-exec: not found

### ISSUE THREAD

**Issue by TorPeeto** [Kong/docker-kong#216] opened 2019-01-16 22:19 UTC
I have my kong database running postgres 9.6

I have tried deploying kong `0.15.0-centos`, and `1.0.0-centos`, and receive the same startup failure for both.

`docker-entrypoint.sh: line 29: exec: su-exec: not found`

Looks like that line may have recently been refactored?  Any input or guidance? 

https://github.com/Kong/docker-kong/blob/691d3b57430ecca159532980f0c891aa1e46612f/centos/docker-entrypoint.sh#L29

**Comment by hbagdi** [comment] 2019-01-16 23:18
#211 which was merged in today fixes the issue.
We are working towards updating the Docker images on Docker Hub, which usually takes a couple of days.

Meanwhile, you can use `0.15.0` and `1.0.0` Docker images which are based on Alpine and don't have this issue.

**Comment by TorPeeto** [comment] 2019-01-31 20:49
Poking to check for any update or timeline here - Alpine images don't seem to play nicely with what we are doing - Is there a holdup to merging the fix and publishing to Dockerhub?  Thanks for any detail.

**Comment by Tieske** [comment] 2019-02-01 09:12
1.0.3 was just released, should arrive shortly on Dockerhub (takes a bit of time)

**Comment by hbagdi** [comment] 2019-02-13 23:11
The issue is now fixed.
Please re-open if otherwise.

**Closed by hbagdi** 2019-02-13 23:11 UTC
