### ISSUE TITLE
the current database schema does not match this version of Kong

### ISSUE THREAD

**Issue by TFarla** [Kong/docker-kong#162] opened 2018-06-02 12:15 UTC
I'm unable to start the kong container because it exits with the following error:

```bash
kong_1            | 2018/06/02 12:11:32 [warn] postgres database 'kong' is missing migration: (rate-limiting) 2015-08-03-132400_init_ratelimiting
kong_1            | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:34: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            | 
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
```

How to reproduce:
1. clone this repo
2. change to compose directory
3. execute `docker-compose up`

System:
- Ubuntu 18.10
- Docker version 17.12.1-ce, build 7390fc6
- Docker-compose version 1.17.1, build unknown

Full docker-compose output:

````bash
docker-compose up 
Creating network "compose_default" with the default driver
Creating compose_consul_1 ... 
Creating compose_kong-database_1 ... 
Creating compose_consul_1
Creating compose_kong-database_1 ... done
Creating compose_nginx-lb_1 ... 
Creating compose_nginx-lb_1 ... done
Creating compose_kong-migration_1 ... 
Creating compose_kong-migration_1 ... done
Creating compose_kong_1 ... 
Creating compose_kong_1 ... done
Attaching to compose_consul_1, compose_kong-database_1, compose_nginx-lb_1, compose_kong-migration_1, compose_kong_1
consul_1          | ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
consul_1          | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
consul_1          | ==> Starting raft data migration...
kong-database_1   | The files belonging to this database system will be owned by user "postgres".
consul_1          | ==> Starting Consul agent...
kong-database_1   | This user must also own the server process.
kong-database_1   | 
nginx-lb_1        | time="2018-06-02T12:11:24Z" level=debug msg="preStart.RunAndWait start" 
kong-migration_1  | migrating core for database kong
consul_1          | ==> Starting Consul agent RPC...
nginx-lb_1        | time="2018-06-02T12:11:24Z" level=debug msg=preStart.Cmd.Run 
kong-database_1   | The database cluster will be initialized with locale "en_US.utf8".
nginx-lb_1        | time="2018-06-02T12:11:24Z" level=debug msg="preStart.RunAndWait end" 
kong-database_1   | The default database encoding has accordingly been set to "UTF8".
consul_1          | ==> Consul agent running!
nginx-lb_1        | time="2018-06-02T12:11:24Z" level=debug msg="nginx.RunAndWait start" 
kong-database_1   | The default text search configuration will be set to "english".
consul_1          |          Node name: '21498b9ed925'
kong-database_1   | 
nginx-lb_1        | time="2018-06-02T12:11:24Z" level=debug msg=nginx.Cmd.Run 
consul_1          |         Datacenter: 'dc1'
kong-database_1   | Data page checksums are disabled.
kong-migration_1  | core migrated up to: 2015-01-12-175310_skeleton
consul_1          |             Server: true (bootstrap: true)
kong-database_1   | 
kong-migration_1  | core migrated up to: 2015-01-12-175310_init_schema
consul_1          |        Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 53, RPC: 8400)
kong-migration_1  | core migrated up to: 2015-11-23-817313_nodes
kong-database_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
consul_1          |       Cluster Addr: 172.18.0.2 (LAN: 8301, WAN: 8302)
kong-migration_1  | core migrated up to: 2016-02-29-142793_ttls
consul_1          |     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
kong-migration_1  | core migrated up to: 2016-09-05-212515_retries
consul_1          |              Atlas: <disabled>
consul_1          | 
consul_1          | ==> Log data will now stream in as it occurs:
kong-migration_1  | core migrated up to: 2016-09-16-141423_upstreams
kong-migration_1  | core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
kong-migration_1  | core migrated up to: 2016-11-11-151900_new_apis_router_1
kong-migration_1  | core migrated up to: 2016-11-11-151900_new_apis_router_2
consul_1          | 
consul_1          |     2018/06/02 12:11:18 [INFO] serf: EventMemberJoin: 21498b9ed925 172.18.0.2
kong-database_1   | creating subdirectories ... ok
consul_1          |     2018/06/02 12:11:18 [INFO] serf: EventMemberJoin: 21498b9ed925.dc1 172.18.0.2
consul_1          |     2018/06/02 12:11:18 [INFO] raft: Node at 172.18.0.2:8300 [Follower] entering Follower state
kong-migration_1  | core migrated up to: 2016-11-11-151900_new_apis_router_3
consul_1          |     2018/06/02 12:11:18 [INFO] consul: adding server 21498b9ed925 (Addr: 172.18.0.2:8300) (DC: dc1)
kong-migration_1  | core migrated up to: 2016-01-25-103600_unique_custom_id
kong-database_1   | selecting default max_connections ... 100
consul_1          |     2018/06/02 12:11:18 [INFO] consul: adding server 21498b9ed925.dc1 (Addr: 172.18.0.2:8300) (DC: dc1)
kong-migration_1  | core migrated up to: 2017-01-24-132600_upstream_timeouts
kong-migration_1  | core migrated up to: 2017-01-24-132600_upstream_timeouts_2
kong-migration_1  | core migrated up to: 2017-03-27-132300_anonymous
kong-database_1   | selecting default shared_buffers ... 128MB
kong-migration_1  | core migrated up to: 2017-04-18-153000_unique_plugins_id
kong-database_1   | selecting dynamic shared memory implementation ... posix
consul_1          |     2018/06/02 12:11:18 [ERR] agent: failed to sync remote state: No cluster leader
kong-migration_1  | core migrated up to: 2017-04-18-153000_unique_plugins_id_2
kong-migration_1  | core migrated up to: 2017-05-19-180200_cluster_events
kong-migration_1  | core migrated up to: 2017-05-19-173100_remove_nodes_table
kong-migration_1  | core migrated up to: 2017-06-16-283123_ttl_indexes
kong-database_1   | creating configuration files ... ok
consul_1          |     2018/06/02 12:11:19 [WARN] raft: Heartbeat timeout reached, starting election
consul_1          |     2018/06/02 12:11:19 [INFO] raft: Node at 172.18.0.2:8300 [Candidate] entering Candidate state
kong-database_1   | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
consul_1          |     2018/06/02 12:11:19 [INFO] raft: Election won. Tally: 1
consul_1          |     2018/06/02 12:11:19 [INFO] raft: Node at 172.18.0.2:8300 [Leader] entering Leader state
kong-database_1   | initializing pg_authid ... ok
consul_1          |     2018/06/02 12:11:19 [INFO] consul: cluster leadership acquired
kong-database_1   | initializing dependencies ... ok
consul_1          |     2018/06/02 12:11:19 [INFO] consul: New leader elected: 21498b9ed925
kong-database_1   | creating system views ... ok
kong-database_1   | loading system objects' descriptions ... ok
consul_1          |     2018/06/02 12:11:19 [INFO] raft: Disabling EnableSingleNode (bootstrap)
consul_1          |     2018/06/02 12:11:19 [INFO] consul: member '21498b9ed925' joined, marking health alive
kong-database_1   | creating collations ... ok
consul_1          |     2018/06/02 12:11:20 [INFO] agent: Synced service 'consul'
kong-database_1   | creating conversions ... ok
kong-database_1   | creating dictionaries ... ok
kong-database_1   | setting privileges on built-in objects ... ok
kong-database_1   | creating information schema ... ok
kong-database_1   | loading PL/pgSQL server-side language ... ok
kong-database_1   | vacuuming database template1 ... ok
kong-database_1   | copying template1 to template0 ... ok
kong-database_1   | copying template1 to postgres ... ok
kong-database_1   | syncing data to disk ... ok
kong-database_1   | 
kong-database_1   | Success. You can now start the database server using:
kong-database_1   | 
kong-database_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
kong-database_1   | 
kong-database_1   | 
kong-database_1   | WARNING: enabling "trust" authentication for local connections
kong-database_1   | You can change this by editing pg_hba.conf or using the option -A, or
kong-database_1   | --auth-local and --auth-host, the next time you run initdb.
kong-database_1   | ****************************************************
kong-database_1   | WARNING: No password has been set for the database.
kong-database_1   |          This will allow anyone with access to the
kong-database_1   |          Postgres port to access your database. In
kong-database_1   |          Docker's default configuration, this is
kong-database_1   |          effectively any other container on the same
kong-database_1   |          system.
kong-database_1   | 
kong-database_1   |          Use "-e POSTGRES_PASSWORD=password" to set
kong-database_1   |          it in "docker run".
kong-database_1   | ****************************************************
kong-database_1   | waiting for server to start....LOG:  database system was shut down at 2018-06-02 12:11:20 UTC
kong-database_1   | LOG:  MultiXact member wraparound protections are now enabled
kong-database_1   | LOG:  autovacuum launcher started
kong-database_1   | LOG:  database system is ready to accept connections
kong-database_1   |  done
kong-database_1   | server started
kong-database_1   | CREATE DATABASE
kong-database_1   | 
kong-database_1   | CREATE ROLE
kong-database_1   | 
kong-database_1   | 
kong-database_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
kong-database_1   | 
kong-database_1   | LOG:  received fast shutdown request
kong-database_1   | waiting for server to shut down...LOG:  aborting any active transactions
kong-database_1   | .LOG:  autovacuum launcher shutting down
kong-database_1   | LOG:  shutting down
kong-database_1   | LOG:  database system is shut down
kong-database_1   |  done
kong-database_1   | server stopped
kong-database_1   | 
kong-database_1   | PostgreSQL init process complete; ready for start up.
kong-database_1   | 
kong-database_1   | LOG:  database system was shut down at 2018-06-02 12:11:22 UTC
kong-database_1   | LOG:  MultiXact member wraparound protections are now enabled
kong-database_1   | LOG:  autovacuum launcher started
kong-database_1   | LOG:  database system is ready to accept connections
kong-migration_1  | core migrated up to: 2017-07-28-225000_balancer_orderlist_remove
kong-migration_1  | core migrated up to: 2017-10-02-173400_apis_created_at_ms_precision
kong-migration_1  | core migrated up to: 2017-11-07-192000_upstream_healthchecks
kong-migration_1  | core migrated up to: 2017-10-27-134100_consistent_hashing_1
kong-migration_1  | core migrated up to: 2017-11-07-192100_upstream_healthchecks_2
kong-migration_1  | core migrated up to: 2017-10-27-134100_consistent_hashing_2
kong-migration_1  | core migrated up to: 2017-09-14-121200_routes_and_services
kong-migration_1  | core migrated up to: 2017-10-25-180700_plugins_routes_and_services
kong-migration_1  | migrating response-transformer for database kong
kong-migration_1  | response-transformer migrated up to: 2016-05-04-160000_resp_trans_schema_changes
kong-migration_1  | migrating ip-restriction for database kong
kong-migration_1  | ip-restriction migrated up to: 2016-05-24-remove-cache
kong-migration_1  | migrating statsd for database kong
kong-migration_1  | statsd migrated up to: 2017-06-09-160000_statsd_schema_changes
kong-migration_1  | migrating jwt for database kong
kong-migration_1  | jwt migrated up to: 2015-06-09-jwt-auth
kong-migration_1  | jwt migrated up to: 2016-03-07-jwt-alg
kong-migration_1  | jwt migrated up to: 2017-05-22-jwt_secret_not_unique
kong-migration_1  | jwt migrated up to: 2017-07-31-120200_jwt-auth_preflight_default
kong_1            | prefix directory /usr/local/kong not found, trying to create it
kong-migration_1  | jwt migrated up to: 2017-10-25-211200_jwt_cookie_names_default
kong-migration_1  | migrating cors for database kong
kong-migration_1  | cors migrated up to: 2017-03-14_multiple_orgins
kong-migration_1  | migrating basic-auth for database kong
kong-migration_1  | basic-auth migrated up to: 2015-08-03-132400_init_basicauth
kong-migration_1  | basic-auth migrated up to: 2017-01-25-180400_unique_username
kong-migration_1  | migrating key-auth for database kong
kong-migration_1  | key-auth migrated up to: 2015-07-31-172400_init_keyauth
kong-migration_1  | key-auth migrated up to: 2017-07-31-120200_key-auth_preflight_default
kong-migration_1  | migrating ldap-auth for database kong
kong-migration_1  | ldap-auth migrated up to: 2017-10-23-150900_header_type_default
kong-migration_1  | migrating hmac-auth for database kong
kong-migration_1  | hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
kong-migration_1  | hmac-auth migrated up to: 2017-06-21-132400_init_hmacauth
kong-migration_1  | migrating datadog for database kong
kong-migration_1  | datadog migrated up to: 2017-06-09-160000_datadog_schema_changes
kong-migration_1  | migrating tcp-log for database kong
kong-migration_1  | tcp-log migrated up to: 2017-12-13-120000_tcp-log_tls
kong-migration_1  | migrating acl for database kong
kong-migration_1  | acl migrated up to: 2015-08-25-841841_init_acl
kong-migration_1  | migrating response-ratelimiting for database kong
kong_1            | 2018/06/02 12:11:32 [warn] postgres database 'kong' is missing migration: (rate-limiting) 2015-08-03-132400_init_ratelimiting
kong_1            | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:34: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            | 
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
kong-migration_1  | response-ratelimiting migrated up to: 2015-08-03-132400_init_response_ratelimiting
kong-migration_1  | response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
kong-migration_1  | response-ratelimiting migrated up to: 2017-12-19-120000_add_route_and_service_id_to_response_ratelimiting
kong-migration_1  | migrating request-transformer for database kong
kong-migration_1  | request-transformer migrated up to: 2016-05-04-160000_req_trans_schema_changes
kong-migration_1  | migrating rate-limiting for database kong
kong-migration_1  | rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
kong-migration_1  | rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
kong-migration_1  | rate-limiting migrated up to: 2017-11-30-120000_add_route_and_service_id
kong-migration_1  | migrating oauth2 for database kong
kong-migration_1  | oauth2 migrated up to: 2015-08-03-132400_init_oauth2
kong-migration_1  | oauth2 migrated up to: 2016-07-15-oauth2_code_credential_id
kong-migration_1  | oauth2 migrated up to: 2016-12-22-283949_serialize_redirect_uri
kong-migration_1  | oauth2 migrated up to: 2016-09-19-oauth2_api_id
kong-migration_1  | oauth2 migrated up to: 2016-12-15-set_global_credentials
kong-migration_1  | oauth2 migrated up to: 2017-04-24-oauth2_client_secret_not_unique
kong-migration_1  | oauth2 migrated up to: 2017-10-19-set_auth_header_name_default
kong-migration_1  | oauth2 migrated up to: 2017-10-11-oauth2_new_refresh_token_ttl_config_value
kong-migration_1  | oauth2 migrated up to: 2018-01-09-oauth2_pg_add_service_id
kong-migration_1  | 62 migrations ran
compose_kong_1 exited with code 1
compose_kong-migration_1 exited with code 0
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=debug msg="nginx.health.run waiting for PID 32: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:11:34 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=debug msg="nginx.health.RunWithTimeout end" 
consul_1          |     2018/06/02 12:11:34 [ERR] http: Request /v1/agent/check/pass/nginx-0229fd030d38?note=ok, error: CheckID does not have associated TTL
nginx-lb_1        | time="2018-06-02T12:11:34Z" level=info msg="Unexpected response code: 500 (CheckID does not have associated TTL)\nService not registered, registering..." 
consul_1          |     2018/06/02 12:11:34 [INFO] agent: Synced service 'nginx-0229fd030d38'
consul_1          |     2018/06/02 12:11:34 [INFO] agent: Synced check 'nginx-0229fd030d38'
nginx-lb_1        | time="2018-06-02T12:11:44Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:11:44Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:11:44Z" level=debug msg="nginx.health.run waiting for PID 37: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:11:44 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:11:44Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:11:44Z" level=debug msg="nginx.health.RunWithTimeout end" 
consul_1          |     2018/06/02 12:11:44 [INFO] agent: Synced check 'nginx-0229fd030d38'
nginx-lb_1        | time="2018-06-02T12:11:54Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:11:54Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:11:54Z" level=debug msg="nginx.health.run waiting for PID 39: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:11:54 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:11:54Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:11:54Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:04Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:04Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:04Z" level=debug msg="nginx.health.run waiting for PID 41: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:04 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:04Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:04Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:14Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:14Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:14Z" level=debug msg="nginx.health.run waiting for PID 43: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:14 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:14Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:14Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:24Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:24Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:24Z" level=debug msg="nginx.health.run waiting for PID 45: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:24 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:24Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:24Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:34Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:34Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:34Z" level=debug msg="nginx.health.run waiting for PID 47: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:34 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:34Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:34Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:44Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:44Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:44Z" level=debug msg="nginx.health.run waiting for PID 49: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:44 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:44Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:44Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:12:54Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:12:54Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:12:54Z" level=debug msg="nginx.health.run waiting for PID 51: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:12:54 +0000] "GET /health HTTP/1.1" 200 97 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:12:54Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:12:54Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:13:04Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:13:04Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:13:04Z" level=debug msg="nginx.health.run waiting for PID 53: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:13:04 +0000] "GET /health HTTP/1.1" 200 100 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:13:04Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:13:04Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:13:14Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:13:14Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:13:14Z" level=debug msg="nginx.health.run waiting for PID 55: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:13:14 +0000] "GET /health HTTP/1.1" 200 100 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:13:14Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:13:14Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:13:24Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:13:24Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:13:24Z" level=debug msg="nginx.health.run waiting for PID 57: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:13:24 +0000] "GET /health HTTP/1.1" 200 100 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:13:24Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:13:24Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:13:34Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:13:34Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:13:34Z" level=debug msg="nginx.health.run waiting for PID 59: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:13:34 +0000] "GET /health HTTP/1.1" 200 100 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:13:34Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:13:34Z" level=debug msg="nginx.health.RunWithTimeout end" 
nginx-lb_1        | time="2018-06-02T12:13:44Z" level=debug msg="nginx.health.RunWithTimeout start" 
nginx-lb_1        | time="2018-06-02T12:13:44Z" level=debug msg=nginx.health.Cmd.Start 
nginx-lb_1        | time="2018-06-02T12:13:44Z" level=debug msg="nginx.health.run waiting for PID 61: " 
nginx-lb_1        | 127.0.0.1 - - [02/Jun/2018:12:13:44 +0000] "GET /health HTTP/1.1" 200 100 "-" "curl/7.52.1"
nginx-lb_1        | time="2018-06-02T12:13:44Z" level=debug msg="nginx.health.run complete" 
nginx-lb_1        | time="2018-06-02T12:13:44Z" level=debug msg="nginx.health.RunWithTimeout end" 

```

**Comment by philbarr** [comment] 2018-07-12 12:50
I changed the compose/kong/Dockerfile line:
CMD /bin/containerpilot kong start
to...
CMD /bin/containerpilot kong start --run-migrations
...and it seems to work for me. I won't submit a pull request though as I'm not sure that's really the correct fix, rather just a workaround.

**Comment by Abdizriel** [comment] 2018-08-05 16:43
I am facing similar problems and unfortunately the change you mention @philbarr didn't helped a lot since kongo sometimes work and sometimes doesn't

**Comment by philbarr** [comment] 2018-08-05 18:45
I also removed the kong-migrations service from docker-compose file if that helps

**Comment by silent-vim** [comment] 2018-10-12 01:04
You can override the command to ensure that the migration happens with kong startup. Here is an example.

 ```
 kong:
    image: kong:latest
    restart: always
    command: >
      sh -c "kong migrations up && sh /docker-entrypoint.sh kong docker-start"
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      kong-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"

```

**Comment by HoussemDellai** [comment] 2019-01-01 20:37
Thank you @silent-vim ! It worked for me !
command: >
     sh -c "kong migrations up && sh /docker-entrypoint.sh kong docker-start"

**Comment by fasimito** [comment] 2019-01-14 10:13
@HoussemDellai and @silent-vim thank you.
the problem seemed resolved by the way with the:
command: >
sh -c "kong migrations up && sh /docker-entrypoint.sh kong docker-start"

but what's the root cause, I am so worry about if this could deploy online. I think it's very dangerous

**Comment by Tieske** [comment] 2019-01-14 18:24
Be careful with the always running of migrations, if more than 1 Kong node run migrations simultaneously, it might destroy your database (before Kong 0.15)

**Comment by hutchic** [comment] 2019-02-15 17:26
our migration process has changed since this was created and has been updated appropriately in docker-compose and docs

**Closed by hutchic** 2019-02-15 17:26 UTC
