### ISSUE TITLE
Exit code 132

### ISSUE THREAD

**Issue by K1LLUM1N471** [Kong/docker-kong#138] opened 2018-01-23 16:04 UTC
Hello,
I tried to start Kong by the step by step tutorial provided on Docker Hub, but failed with Exit Code 132 in the second step.

STEP 1
docker run \
-d \
--name kong-database \
-p 5432:5432 \
-e "POSTGRES_USER=kong" \
-e "POSTGRES_DB=kong" \
postgres:9.5

docker events
>  2018-01-23T16:38:54.953589830+01:00`
>  container create 516ffcf932df5925b2506d08701b71bfe0474b54bd756e02863718abaec7e945 (image=postgres:9.5, name=kong-database)
> 2018-01-23T16:38:54.998145199+01:00 network connect abab09b4fcf2401ad240a610cb841ba933612defb1699f90b5722b174283cb93 (container=516ffcf932df5925b2506d08701b71bfe0474b54bd756e02863718abaec7e945, name=bridge, type=bridge)
> 2018-01-23T16:38:55.001461308+01:00 volume mount c2219608a977d5e4298c5800edebe8b1dac19d9827e9def1160853a0e79e04e6 (container=516ffcf932df5925b2506d08701b71bfe0474b54bd756e02863718abaec7e945, destination=/var/lib/postgresql/data, driver=local, propagation=, read/write=true)
> 2018-01-23T16:38:55.333484099+01:00 container start 516ffcf932df5925b2506d08701b71bfe0474b54bd756e02863718abaec7e945 (image=postgres:9.5, name=kong-database)

STEP 2
docker run \
--rm \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
kong:latest kong migrations up

docker events
> 2018-01-23T16:39:47.250727778+01:00 container create 0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be (build-date=20180107, image=kong:latest, license=GPLv2, name=unruffled_pasteur, vendor=CentOS)
> 2018-01-23T16:39:47.253354925+01:00 container attach 0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be (build-date=20180107, image=kong:latest, license=GPLv2, name=unruffled_pasteur, vendor=CentOS)
> 2018-01-23T16:39:47.282144719+01:00 network connect abab09b4fcf2401ad240a610cb841ba933612defb1699f90b5722b174283cb93 (container=0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be, name=bridge, type=bridge)
> 2018-01-23T16:39:47.616824592+01:00 container start 0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be (build-date=20180107, image=kong:latest, license=GPLv2, name=unruffled_pasteur, vendor=CentOS)
> 2018-01-23T16:39:47.990398770+01:00 container die 0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be (build-date=20180107, exitCode=132, image=kong:latest, license=GPLv2, name=unruffled_pasteur, vendor=CentOS)
> 2018-01-23T16:39:48.117972395+01:00 network disconnect abab09b4fcf2401ad240a610cb841ba933612defb1699f90b5722b174283cb93 (container=0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be, name=bridge, type=bridge)
> 2018-01-23T16:39:48.189329801+01:00 container destroy 0eb1ff72b58858d46d5f2fe6190b5613d2a3bb63fef52077b57612c0dc7ef7be (build-date=20180107, image=kong:latest, license=GPLv2, name=unruffled_pasteur, vendor=CentOS)
> 

STEP 3
docker run \
--name kong \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-p 8000:8000 \
-p 8443:8443 \
-p 8001:8001 \
-p 8444:8444 \
kong

docker events
> 2018-01-23T16:45:17.470520781+01:00 container create 9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc (build-date=20180107, image=kong, license=GPLv2, name=kong, vendor=CentOS)
> 2018-01-23T16:45:17.473171128+01:00 container attach 9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc (build-date=20180107, image=kong, license=GPLv2, name=kong, vendor=CentOS)
> 2018-01-23T16:45:17.555660423+01:00 network connect abab09b4fcf2401ad240a610cb841ba933612defb1699f90b5722b174283cb93 (container=9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc, name=bridge, type=bridge)
> 2018-01-23T16:45:17.845075412+01:00 container start 9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc (build-date=20180107, image=kong, license=GPLv2, name=kong, vendor=CentOS)
> 2018-01-23T16:45:18.216602759+01:00 container die 9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc (build-date=20180107, exitCode=132, image=kong, license=GPLv2, name=kong, vendor=CentOS)
> 2018-01-23T16:45:18.397790747+01:00 network disconnect abab09b4fcf2401ad240a610cb841ba933612defb1699f90b5722b174283cb93 (container=9d4de302f6d195f8eb69145056eaa089f26f2a56e8dbcfc4e40ca3a9db10dddc, name=bridge, type=bridge)

System:
Lubuntu 16.04 LTS (64 Bit)
4.13.0-26-generic

Do you have any suggestions for me?

Kind regards,
K1llum1n471

**Comment by salazar** [comment] 2018-01-23 18:13
@K1LLUM1N471 could you provide us with logs - obtained, for instance, with `docker logs`?

**Comment by K1LLUM1N471** [comment] 2018-01-24 13:16
Sure, here they are.

// STEP 1
docker logs kong-database
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.utf8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory /var/lib/postgresql/data ... ok
> creating subdirectories ... ok
> selecting default max_connections ... 100
> selecting default shared_buffers ... 128MB
> selecting dynamic shared memory implementation ... posix
> creating configuration files ... ok
> creating template1 database in /var/lib/postgresql/data/base/1 ... ok
> initializing pg_authid ... ok
> initializing dependencies ... ok
> creating system views ... ok
> loading system objects' descriptions ... ok
> creating collations ... ok
> creating conversions ... ok
> creating dictionaries ... ok
> setting privileges on built-in objects ... ok
> creating information schema ... ok
> loading PL/pgSQL server-side language ... ok
> vacuuming database template1 ... ok
> copying template1 to template0 ... ok
> copying template1 to postgres ... ok
> 
> WARNING: enabling "trust" authentication for local connections
> You can change this by editing pg_hba.conf or using the option -A, or
> --auth-local and --auth-host, the next time you run initdb.
> syncing data to disk ... ok
> 
> Success. You can now start the database server using:
> 
>     pg_ctl -D /var/lib/postgresql/data -l logfile start
> 
> ****************************************************
> WARNING: No password has been set for the database.
>          This will allow anyone with access to the
>          Postgres port to access your database. In
>          Docker's default configuration, this is
>          effectively any other container on the same
>          system.
> 
>          Use "-e POSTGRES_PASSWORD=password" to set
>          it in "docker run".
> ****************************************************
> waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
> HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.

 // STEP 2
docker logs kong-database
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.utf8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory /var/lib/postgresql/data ... ok
> creating subdirectories ... ok
> selecting default max_connections ... 100
> selecting default shared_buffers ... 128MB
> selecting dynamic shared memory implementation ... posix
> creating configuration files ... ok
> creating template1 database in /var/lib/postgresql/data/base/1 ... ok
> initializing pg_authid ... ok
> initializing dependencies ... ok
> creating system views ... ok
> loading system objects' descriptions ... ok
> creating collations ... ok
> creating conversions ... ok
> creating dictionaries ... ok
> setting privileges on built-in objects ... ok
> creating information schema ... ok
> loading PL/pgSQL server-side language ... ok
> vacuuming database template1 ... ok
> copying template1 to template0 ... ok
> copying template1 to postgres ... ok
> 
> WARNING: enabling "trust" authentication for local connections
> You can change this by editing pg_hba.conf or using the option -A, or
> --auth-local and --auth-host, the next time you run initdb.
> syncing data to disk ... ok
> 
> Success. You can now start the database server using:
> 
>     pg_ctl -D /var/lib/postgresql/data -l logfile start
> 
> ****************************************************
> WARNING: No password has been set for the database.
>          This will allow anyone with access to the
>          Postgres port to access your database. In
>          Docker's default configuration, this is
>          effectively any other container on the same
>          system.
> 
>          Use "-e POSTGRES_PASSWORD=password" to set
>          it in "docker run".
> ****************************************************
> waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
> HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
> LOG:  database system was shut down at 2018-01-24 13:03:21 UTC
> LOG:  MultiXact member wraparound protections are now enabled
> LOG:  database system is ready to accept connections
> LOG:  autovacuum launcher started
>  done
> server started
> CREATE DATABASE
> 
> CREATE ROLE
> 
> 
> /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
> 
> LOG:  received fast shutdown request
> waiting for server to shut down....LOG:  aborting any active transactions
> LOG:  autovacuum launcher shutting down
> LOG:  shutting down
> LOG:  database system is shut down
>  done
> server stopped
> 
> PostgreSQL init process complete; ready for start up.
> 
> LOG:  database system was shut down at 2018-01-24 13:03:23 UTC
> LOG:  MultiXact member wraparound protections are now enabled
> LOG:  database system is ready to accept connections
> LOG:  autovacuum launcher started

docker logs kong
--> EMPTY

**Comment by salazar** [comment] 2018-01-24 18:42
@K1LLUM1N471 if I understood well, the migrations step failed; do you see any output at all when you run it? It's expected that there will be no logs, after all the `--rm` flag will remove the container after it exits.

**Comment by K1LLUM1N471** [comment] 2018-01-30 10:42
I repeated all steps again. This time I removed the parameter '-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" ' in step 1 & 2.
The output of step 2 ended with "58 migrations ran".
When I try step 3, "docker logs kong" says: 

> 2018/01/30 09:44:58 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:159: bad argument #2 to 'assert' (string expected, got table)
> stack traceback:
> 	[C]: in function 'assert'
> 	/usr/local/share/lua/5.1/kong/init.lua:159: in function 'init'
> 	init_by_lua:3: in main chunk
> nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:159: bad argument #2 to 'assert' (string expected, got table)
> stack traceback:
> 	[C]: in function 'assert'
> 	/usr/local/share/lua/5.1/kong/init.lua:159: in function 'init'
> 	init_by_lua:3: in main chunk

**Comment by iagocavalcante** [comment] 2018-02-02 20:40
I have the same problem here. I'm try to run docker-compose, kong-database run fine, but kong-migration returns error.

`version: '2.2'

services:
  
  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5    

  kong-migration:
    image: kong
    depends_on:
      kong-database:
        condition: service_healthy
    links:
      - kong-database:kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  `

This is my terminal when i run docker-compose up

`Starting gateway_kong-database_1 ... done
Starting gateway_kong-migration_1 ... done
Attaching to gateway_kong-database_1, gateway_kong-migration_1
kong-database_1   | LOG:  database system was shut down at 2018-02-02 14:39:13 UTC
kong-database_1   | LOG:  MultiXact member wraparound protections are now enabled
kong-database_1   | LOG:  database system is ready to accept connections
kong-database_1   | LOG:  autovacuum launcher started
gateway_kong-migration_1 exited with code 132
`

**Comment by ChengEnHe** [comment] 2018-05-24 01:44
I have the same issue, and I google the result.I found a article as below https://medium.com/@nprch_12/docker-exited-132-e38f9dd2cd0d.
It said this error about your PC cpu version too old to run kong at docker.
Is it true??Can I downgrade the version of kong to run at docker??

**Comment by find456789** [comment] 2018-11-26 06:07
I have the same issue

macbook pro mojave,

Docker version 18.09.0, build 4d60db4

![image](https://user-images.githubusercontent.com/6580897/48995813-783c6080-f184-11e8-895c-192dc50c2477.png)

**Comment by kmalhi** [comment] 2018-12-19 20:15
Im having a similar issue with Exited(132) error when trying to run the Kong container

**Comment by hutchic** [comment] 2018-12-20 15:42
Unable to reproduce with the following:

```
docker run -d --name kong-database \
-p 5432:5432 \
-e "POSTGRES_USER=kong" \
-e "POSTGRES_DB=kong" \
postgres:9.5

docker run -t --rm \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
kong kong migrations up

docker run -d \
--name kong \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stdout" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stdout" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
-p 8001:8001 \
-p 8000:8000 \
kong

curl localhost:8000
curl localhost:8001

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
```

**Comment by Tieske** [comment] 2018-12-21 15:48
The cpu needs SSE4.2 support, see http://www.cpu-world.com/Glossary/S/SSE4.2.html

You can compile openresty from source if you have a very *old* machine in this case, because the lack of instruction support is factored in at compile time.

**Comment by DonMartin76** [comment] 2019-02-04 16:15
We just experienced this on one of our Kubernetes clusters as well; turns out the hoster had sold us some really old virtual hardware, and that the CPUs were really lacking `sse4_2` (Opteron 23xx).

**Comment by hutchic** [comment] 2019-02-07 15:04
@DonMartin76 that's rough :(

I'm going to go ahead and close this issue. At this time we don't have any plans on compiling for CPU's that lack SSE4.2

**Closed by hutchic** 2019-02-07 15:04 UTC

**Comment by DonMartin76** [comment] 2019-02-07 16:49
Of course. It's good this information is available here. Found it via googling the exit code. Thank you @Tieske for posting this. We managed to upgrade the cluster to intel based nodes, and now everything works as expected.
