### ISSUE TITLE
Cannot access Kong Manager 

### ISSUE THREAD

**Issue by kameshbrao** [Kong/docker-kong#586] opened 2022-08-16 15:51 UTC
Iam trying to build the kong image using the alpine Dockerfile but then I cannot access the admin manager and the port 8002 is not available.

**Comment by vitordesousa** [comment] 2022-09-12 22:36
Me too..

I added

`admin_gui_url = http://localhost:8002`
only and tested. and with above code
`admin_listen = 0.0.0.0:8001 reuse port backlog=16384, 0.0.0.0:8444 http2 ssl reuse port backlog=16384`

I try open 8002 on docker compose file e not resolved..

v2.8.1

**Comment by kameshbrao** [comment] 2022-09-13 03:54
Correct, opening 8002 port in docker file has no impact. Can someone help on this topic?

**Comment by shahamit** [comment] 2022-09-27 12:25
I am also struggling to enable kong manager on the kong gateway. It seems kong manager is available only on the kong enterprise free mode and not in the kong OSS version. Hence we need to use enterprise kong images

**Below are the docker commands to start the database and kong gateway**

docker network create kong-quickstart-net 

docker run -d --name kong-quickstart-database --network=kong-quickstart-net -e POSTGRES_DB=kong -e POSTGRES_USER=kong -e POSTGRES_PASSWORD=kong postgres:14.4-bullseye 

docker run --rm --network=kong-quickstart-net -e KONG_DATABASE=postgres --env-file kong-quickstart.env kong/kong-gateway:3.0.0.0-alpine kong migrations bootstrap 

docker run -d --name kong-quickstart-gateway --network=kong-quickstart-net --env-file kong-quickstart.env -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8003:8003 -p 8004:8004 kong/kong-gateway:3.0.0.0-alpine

**Below is the environment file**

############################################################################## # 
The following env file was used during docker run to set the container # environment for Kong Gateway ############################################################################## 
KONG_DATABASE=postgres 
KONG_PG_HOST=kong-quickstart-database 
KONG_PG_USER=kong 
KONG_PG_PASSWORD=kong 
KONG_ADMIN_LISTEN=[0.0.0.0:8001](http://0.0.0.0:8001/), [0.0.0.0:8444](http://0.0.0.0:8444/) ssl KONG_PROXY_ACCESS_LOG=/dev/stdout KONG_ADMIN_ACCESS_LOG=/dev/stdout KONG_PROXY_ERROR_LOG=/dev/stderr KONG_ADMIN_ERROR_LOG=/dev/stderr

_________________________________________________________________________________________

Accessing http://localhost:8002 shows up the kong manager.

**Comment by kameshbrao** [comment] 2022-09-27 14:21
But doesnt enterprise images need a license?

**Comment by gszr** [comment] 2022-09-27 14:26
Hey @kameshbrao,

Kong Manager is not available in our OSS image, only in Kong Gateway "Free Mode" -- which you get by running the enterprise image without a license. You can learn more about available modes here: https://docs.konghq.com/gateway/latest/#packages-and-modes.

I am closing this issue for now since this is not a bug.

Cheers!

**Comment by gszr** [comment] 2022-09-27 14:27
Note:

`docker pull kong` -> this one points to our OSS official image
`docker pull kong/kong-gateway` -> this one (as used by @shahamit above) points to the Kong Gateway image, which can be started in Free Mode

**Closed by gszr** 2022-09-27 14:26 UTC

**Comment by shahamit** [comment] 2022-09-28 08:37
@gszr - I have a question related to this docker based deployment - how do we add multiple kong instances such that they act as one cluster? If one of the kong instances crashes, another kong instance is able to serve the requests. Ultimately not making kong as a single point of failure. I assume that's possible to do when running kong in free mode.

Thanks.
