### ISSUE TITLE
Error in nginx with go plugin through docker compose

### ISSUE THREAD

**Issue by marciojusto** [Kong/docker-kong#518] opened 2021-10-29 14:54 UTC
`2021/10/29 14:34:30 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/10/29 14:34:30 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/protoc.lua:334: module load error: google/protobuf/descriptor.proto
	google/protobuf/descriptor.proto: No such file or directory
	./google/protobuf/descriptor.proto: No such file or directory
	/usr/include/google/protobuf/descriptor.proto: No such file or directory
	/usr/local/opt/protobuf/include//google/protobuf/descriptor.proto: No such file or directory
	/usr/local/kong/lib//google/protobuf/descriptor.proto: No such file or directory
	kong/google/protobuf/descriptor.proto: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/protoc.lua:334: in function 'parsefile'
	/usr/local/share/lua/5.1/protoc.lua:505: in function 'top_parser'
	/usr/local/share/lua/5.1/protoc.lua:846: in function 'parse'
	/usr/local/share/lua/5.1/protoc.lua:324: in function 'parsefile'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:171: in function 'load_service'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:263: in function 'new'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:116: in function 'get_server_rpc'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:218: in function 'build_phases'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:264: in function 'get_plugin'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:271: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:514: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/protoc.lua:334: module load error: google/protobuf/descriptor.proto
	google/protobuf/descriptor.proto: No such file or directory
	./google/protobuf/descriptor.proto: No such file or directory
	/usr/include/google/protobuf/descriptor.proto: No such file or directory
	/usr/local/opt/protobuf/include//google/protobuf/descriptor.proto: No such file or directory
	/usr/local/kong/lib//google/protobuf/descriptor.proto: No such file or directory
	kong/google/protobuf/descriptor.proto: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/protoc.lua:334: in function 'parsefile'
	/usr/local/share/lua/5.1/protoc.lua:505: in function 'top_parser'
	/usr/local/share/lua/5.1/protoc.lua:846: in function 'parse'
	/usr/local/share/lua/5.1/protoc.lua:324: in function 'parsefile'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:171: in function 'load_service'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:263: in function 'new'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:116: in function 'get_server_rpc'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:218: in function 'build_phases'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:264: in function 'get_plugin'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:271: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:514: in function 'init'
	init_by_lua:3: in main chunk`

My docker compose:

version: "3.7"

services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ./go-wait:/usr/local/bin/go-wait
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=go-wait
      - KONG_PLUGINSERVER_NAMES=go-wait
      - KONG_PLUGINSERVER_GO_WAIT_QUERY_CMD=/usr/local/bin/go-wait -dump
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8044 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

**Comment by gszr** [comment] 2021-11-10 13:20
Hey @marciojusto,

Thank you for reporting this issue. The root cause is that Kong packages didn't include protobuf includes (see, for example,  `No such file or directory ./google/protobuf/descriptor.proto`). This is fixed by https://github.com/Kong/kong-build-tools/pull/409 and will be available in an upcoming release - 2.6.1 or 2.7.0, whichever comes first. In the meantime, you would need to install the protobut-devel package yourself (the name varies depending on the image you are using).

Cheers

**Comment by marciojusto** [comment] 2021-11-10 13:25
Thanks for the response @gszr.

I did a downgrade of kong go-pdk to 0.6.1 and it's solved my problem!

**Comment by gszr** [comment] 2021-11-24 12:07
Glad it solved the issue, @marciojusto! Closing this for now,

**Closed by gszr** 2021-11-24 12:07 UTC
